### ISSUE TITLE
I have installed nuclei, but I am getting an error when trying to import it. I couldn't find the package after installation.？

### ISSUE THREAD

**Issue by wjbhydj** [kushvaibhav/PyNuclei#1]
pip install PyNuclei
    from PyNuclei import Nuclei
ModuleNotFoundError: No module named 'PyNuclei'

**Comment by nrathaus** [comment]
It seems that the `pip` package is broken

**Comment by nrathaus** [comment]
I fixed the issue:
https://github.com/kushvaibhav/PyNuclei/pull/2

It is related to incorrect use of `setup.py`, you can install from the git repository, or wait for the merge and upload to pypi

**Comment by kushvaibhav** [comment]
Fixed in PyNuclei 1.3 release version
